#include "OverdriveEffect.h"

#include <algorithm>
#include <cmath>

namespace {
constexpr float kPi = 3.14159265358979323846f;
constexpr int32_t kUpdateInterval = 32;
constexpr float kParameterSmoothingSeconds = 0.020f;
constexpr float kBypassFadeSeconds = 0.010f;
}

void OverdriveEffect::prepare(double sampleRate, int32_t) {
    sampleRate_ = static_cast<float>(std::max(1.0, sampleRate));
    driveCurrent_ = driveTarget_.load(std::memory_order_relaxed);
    toneCurrent_ = toneTarget_.load(std::memory_order_relaxed);
    levelCurrent_ = levelTarget_.load(std::memory_order_relaxed);
    wetMix_ = isEnabled() ? 1.0f : 0.0f;
    samplesUntilUpdate_ = 0;

    // 20 Hz high-pass filter to remove DC generated by nonlinear processing.
    const float cutoff = 20.0f;
    const float k = std::tan(kPi * cutoff / sampleRate_);
    const float norm = 1.0f / (1.0f + k);
    dcBlocker_.setCoefficients(norm, -norm, 0.0f, (k - 1.0f) * norm, 0.0f);
    updateToneFilter();
    reset();
}

void OverdriveEffect::reset() {
    dcBlocker_.reset();
    toneLowPass_.reset();
}

float OverdriveEffect::processSample(float input) noexcept {
    if (--samplesUntilUpdate_ <= 0) {
        samplesUntilUpdate_ = kUpdateInterval;
        updateSmoothedParameters();
        updateToneFilter();
    }

    const float driveNormalized = driveCurrent_ * 0.01f;
    const float preGain = std::pow(10.0f, (6.0f + 30.0f * driveNormalized) / 20.0f);
    const float normalization = 1.0f / std::tanh(std::max(1.0f, preGain));
    const float clipped = std::tanh(input * preGain) * normalization;
    const float dcFiltered = dcBlocker_.process(clipped);
    const float toneFiltered = toneLowPass_.process(dcFiltered);
    const float wet = toneFiltered * percentToLevelGain(levelCurrent_);

    const float targetMix = isEnabled() ? 1.0f : 0.0f;
    const float mixCoefficient =
            1.0f - std::exp(-1.0f / (kBypassFadeSeconds * sampleRate_));
    wetMix_ += (targetMix - wetMix_) * mixCoefficient;

    return input * (1.0f - wetMix_) + wet * wetMix_;
}

void OverdriveEffect::setParameters(
        float drivePercent,
        float tonePercent,
        float levelPercent
) noexcept {
    driveTarget_.store(std::clamp(drivePercent, 0.0f, 100.0f), std::memory_order_relaxed);
    toneTarget_.store(std::clamp(tonePercent, 0.0f, 100.0f), std::memory_order_relaxed);
    levelTarget_.store(std::clamp(levelPercent, 0.0f, 100.0f), std::memory_order_relaxed);
}

void OverdriveEffect::updateSmoothedParameters() noexcept {
    const float blockSeconds = static_cast<float>(kUpdateInterval) / sampleRate_;
    const float smoothing =
            1.0f - std::exp(-blockSeconds / kParameterSmoothingSeconds);

    driveCurrent_ +=
            (driveTarget_.load(std::memory_order_relaxed) - driveCurrent_) * smoothing;
    toneCurrent_ +=
            (toneTarget_.load(std::memory_order_relaxed) - toneCurrent_) * smoothing;
    levelCurrent_ +=
            (levelTarget_.load(std::memory_order_relaxed) - levelCurrent_) * smoothing;
}

void OverdriveEffect::updateToneFilter() noexcept {
    // 700 Hz at 0%, approximately 8 kHz at 100%.
    const float normalized = toneCurrent_ * 0.01f;
    const float cutoff = 700.0f * std::pow(8000.0f / 700.0f, normalized);
    const float q = 0.70710678f;
    const float omega = 2.0f * kPi * cutoff / sampleRate_;
    const float cosine = std::cos(omega);
    const float alpha = std::sin(omega) / (2.0f * q);
    const float b0 = (1.0f - cosine) * 0.5f;
    const float b1 = 1.0f - cosine;
    const float b2 = (1.0f - cosine) * 0.5f;
    const float a0 = 1.0f + alpha;
    const float a1 = -2.0f * cosine;
    const float a2 = 1.0f - alpha;

    toneLowPass_.setCoefficients(
            b0 / a0,
            b1 / a0,
            b2 / a0,
            a1 / a0,
            a2 / a0
    );
}

float OverdriveEffect::percentToLevelGain(float percent) noexcept {
    // 50% is approximately unity, 0% is silence, 100% is +6 dB.
    if (percent <= 0.0f) {
        return 0.0f;
    }
    const float db = -30.0f + 36.0f * (percent * 0.01f);
    return std::pow(10.0f, db / 20.0f);
}
